name: Trigger auto deployment for nh173-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nh173-api-AutoDeployTrigger-5a31b6a4-a528-4fcc-a388-98bf712ca6b5.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: nh173.azurecr.io
          username: ${{ secrets.NH173API_REGISTRY_USERNAME }}
          password: ${{ secrets.NH173API_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nh173.azurecr.io/nh173-api:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NH173API_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n nh173-api -g nils-hjalmarsson-173-containers --server nh173.azurecr.io --username  ${{ secrets.NH173API_REGISTRY_USERNAME }} --password ${{ secrets.NH173API_REGISTRY_PASSWORD }}
            az containerapp update -n nh173-api -g nils-hjalmarsson-173-containers --image nh173.azurecr.io/nh173-api:${{ github.sha }}
